version: '3.4'
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      OPS: "2533274795524562"
    ports:
      - 19132:19132/udp
    volumes:
      - minecraft-data:/data
    stdin_open: true
    tty: true

  web:
    container_name: web-server
    image: joseluisq/static-web-server
    environment:
      SERVER_LOG_LEVEL: trace
    #  SERVER_HOST: "137.184.112.202"
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - web:/public

volumes:
  minecraft-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/minecraft'
  web:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/minecraft/web'
